### ISSUE TITLE
Getting "Metrics already registered" error frequently

### ISSUE THREAD

**Issue by dashrathc** [groupon/spark-metrics#22]
Have integrated spark-metrics for Spark 1.6 in SparkApplication and managing job using Spark Job Server. Encountering following error frequently

[2017-06-22 13:37:24,576] INFO  park.metrics.MetricsSystem [] [akka://JobServer/user/context-supervisor/app-context] - Metrics already registered
java.lang.IllegalArgumentException: A metric named app-20170622133325-0035.driver.ccm-context.App.sampleCounter-20170622_133720 already exists
        at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
        at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:389)
        at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
        at org.apache.spark.metrics.MetricsSystem.registerSource(MetricsSystem.scala:152)
        at org.apache.spark.groupon.metrics.MetricsReceiver.registerMetricSource(MetricsReceiver.scala:170)
        at org.apache.spark.groupon.metrics.MetricsReceiver$$anonfun$getOrCreateCounter$1.apply(MetricsReceiver.scala:118)
        at org.apache.spark.groupon.metrics.MetricsReceiver$$anonfun$getOrCreateCounter$1.apply(MetricsReceiver.scala:116)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at org.apache.spark.groupon.metrics.MetricsReceiver.getOrCreateCounter(MetricsReceiver.scala:116)
        at org.apache.spark.groupon.metrics.MetricsReceiver$$anonfun$receive$1.applyOrElse(MetricsReceiver.scala:97)
        at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:116)
        at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:204)
        at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
        at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Could anyone please help out to resolve this issue

**Comment by sareddy7** [comment]
I have noticed that for some of my spark batch job runs when this error condition is met, my metrics are incorrect(counter values are less than what they should be, but when spark does not hit this error throughout the life of my job all counter values are accurate.

**Comment by sareddy7** [comment]
I verified that the issue has nothing to do with the exporter for prometheus/grafana by turning csv sink on. 
My batch job runs for about 30 seconds, runs where the counter value is correct has 2 metric events in csv, but the runs for which this error occurs there is only one metric event. So I am assuming even though this error is logged as INFO its actual  an ERROR condition at least from the library perspective. I am not entirely sure why this happens, I glanced through [org.apache.spark.groupon.metrics.MetricsReceiver](https://github.com/groupon/spark-metrics/blob/master/src/main/scala/org/apache/spark/groupon/metrics/MetricsReceiver.scala#L169) but was not able to figure how this happens in the first place.

**Comment by sareddy7** [comment]
@akakitani 
I am guessing the spark [MetricSystem.register](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/metrics/MetricsSystem.scala#L160) call needs to be updated to use [MetricRegistry.getOrAdd](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L417). 

Could you please share your thoughts on this?

**Comment by sareddy7** [comment]
I am afraid we cannot do that, spark 2.1 still depends on codahale metrics 3.1, MetricRegistry.getOrAdd is only added in 3.2. See [PR 1023](https://github.com/dropwizard/metrics/pull/1023/files)

**Comment by mmartsen** [comment]
MetricsExampleApp also fails with similar error

**Comment by NoamShaish** [comment]
I have created a [pull request](https://github.com/groupon/spark-metrics/pull/24) fixing this issue.
Briefly the issue here was concurrency, by keeping the java concurrent hash map I could use compute if absent and achieve the same functionality in a thread safe manner.
@akakitani please review

**Comment by nikita-clearscale** [comment]
With this issue all library does not work at all I can not believe that nobody spot this issue before. Are there any workarounds? (may be with old library version?)
